### ISSUE TITLE
No module named 'cpython'

### ISSUE THREAD

**Issue by csala** [rogerhu/gdb-heap#19]
This is probably also related to #18 and the migration of gdb to python 3 stated by @rogerhu.

The question is that I tried the same commands sequence as in #18 in a different machine, and this is what I got:

```
(gdb) heap
Blocks retrieved 10000
Blocks retrieved 20000
Blocks retrieved 30000
Blocks retrieved 40000
Blocks retrieved 50000
Blocks analyzed 10000
Blocks analyzed 20000
Blocks analyzed 30000
Blocks analyzed 40000
Blocks analyzed 50000
Traceback (most recent call last):
  File "gdb-heap/heap/commands.py", line 34, in g
    return f(self, args, from_tty)
  File "gdb-heap/heap/commands.py", line 56, in invoke
    usage_list = list(lazily_get_usage_list())
  File "gdb-heap/heap/__init__.py", line 503, in lazily_get_usage_list
    categorize_usage_list(usage_list)
  File "gdb-heap/heap/__init__.py", line 536, in categorize_usage_list
    from cpython import python_categorization
ImportError: No module named 'cpython'
Error occurred in Python command: No module named 'cpython'
```

**Comment by rogerhu** [comment]
Fixed by https://github.com/rogerhu/gdb-heap/pull/20.  Thanks again for the pull request!
