### ISSUE TITLE
No symbol "main_arena" in current context.

### ISSUE THREAD

**Issue by annemacedo-tw** [rogerhu/gdb-heap#30]
I currently have a docker setup with GDB, like [this](https://gist.github.com/retpolanne/8eab7d0dbcd7f4f7fa6f21adf7759674#gdb-using-docker-and-colima)

I'm trying to debug a python3 app, I have python3-dbg installed on the docker container with GDB. 

```
[Current thread is 1 (LWP 9335)]
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/home/gdb-heap/gdbheap.py", line 17, in <module>
    from heap.commands import register_commands
  File "/home/gdb-heap/heap/commands.py", line 21, in <module>
    from heap.glibc import glibc_arenas
  File "/home/gdb-heap/heap/glibc.py", line 445, in <module>
    glibc_arenas = GlibcArenas()
  File "/home/gdb-heap/heap/glibc.py", line 415, in __init__
    self.main_arena = self.get_main_arena()
  File "/home/gdb-heap/heap/glibc.py", line 420, in get_main_arena
    return gdb.parse_and_eval("main_arena")
gdb.error: No symbol "main_arena" in current context.
/home/gdb-heap-commands:7: Error in sourced command file:
```

Seems similar to https://github.com/hugsy/gef/issues/81

**Comment by rogerhu** [comment]
The commit that mostly flags an exception for the link you mentioned is here: https://github.com/SakiiR/gef/commit/c373f0c261fa5c058937e0d2d1129b80efa5b493

Are you generating the core dump from inside/outside the container? Are you using gdb with access to the debug version of libc as well?

 https://stackoverflow.com/questions/37960788/why-there-isnt-main-arena-in-libc-so-symbol-table-while-there-is-one-in-malloc

**Comment by retpolanne** [comment]
Hey @rogerhu . 

I'm generating the core dump from inside the container. I believe I was using gdb with debug libc.
